"""initial schema — Phase 1

Creates every table defined in the handoff §5. Written by hand rather
than autogenerated so each decision is visible and explained.

Design highlights repeated here for auditability (originals in model
docstrings):
    - pgcrypto is installed for gen_random_uuid() (built-in on PG 13+,
      but the extension line is cheap insurance).
    - Every tenant-scoped table has user_id NOT NULL + FK CASCADE DELETE
      → deleting a user truly erases their data (GDPR Art. 17).
    - Every table has created_at (and updated_at where the row mutates).
    - Indexes are added on every FK column we filter by — Postgres does
      NOT auto-index FKs, which surprises people and kills query plans.

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-15 12:00:00
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgcrypto provides gen_random_uuid(). CREATE EXTENSION is idempotent.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # --- users ---------------------------------------------------------
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("is_verified", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("google_calendar_credentials", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_users_email", "users", ["email"])

    # --- profiles ------------------------------------------------------
    op.create_table(
        "profiles",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("cv_raw_text", sa.Text, nullable=True),
        sa.Column("cv_file_path", sa.String(500), nullable=True),
        sa.Column("structured_data", postgresql.JSONB, nullable=True),
        sa.Column("skills_hard", postgresql.JSONB, nullable=True),
        sa.Column("skills_soft", postgresql.JSONB, nullable=True),
        sa.Column("seniority_level", sa.String(50), nullable=True),
        sa.Column("salary_min", sa.Integer, nullable=True),
        sa.Column("salary_ideal", sa.Integer, nullable=True),
        sa.Column("location_preferences", postgresql.JSONB, nullable=True),
        sa.Column("remote_preference", sa.String(20), nullable=True),
        sa.Column("notice_period", sa.String(50), nullable=True),
        sa.Column("career_goals", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_profiles_user_id", "profiles", ["user_id"])

    # --- profile_answers ----------------------------------------------
    op.create_table(
        "profile_answers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("question", sa.Text, nullable=False),
        sa.Column("answer", sa.Text, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_profile_answers_user_id", "profile_answers", ["user_id"])

    # --- jobs ----------------------------------------------------------
    op.create_table(
        "jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("company", sa.String(255), nullable=False),
        sa.Column("location", sa.String(255), nullable=True),
        sa.Column("salary_min", sa.Integer, nullable=True),
        sa.Column("salary_max", sa.Integer, nullable=True),
        sa.Column("salary_raw", sa.String(100), nullable=True),
        sa.Column("description_raw", sa.Text, nullable=False),
        sa.Column("source_url", sa.String(1000), nullable=True),
        sa.Column("source_type", sa.String(20), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="saved"),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_jobs_user_id", "jobs", ["user_id"])

    # --- job_scores ----------------------------------------------------
    op.create_table(
        "job_scores",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("jobs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("total_score", sa.Integer, nullable=False),
        sa.Column("skills_score", sa.Integer, nullable=False),
        sa.Column("experience_score", sa.Integer, nullable=False),
        sa.Column("salary_score", sa.Integer, nullable=False),
        sa.Column("location_score", sa.Integer, nullable=False),
        sa.Column("culture_score", sa.Integer, nullable=False),
        sa.Column("trajectory_score", sa.Integer, nullable=False),
        sa.Column("strengths", postgresql.JSONB, nullable=True),
        sa.Column("weaknesses", postgresql.JSONB, nullable=True),
        sa.Column("red_flags", postgresql.JSONB, nullable=True),
        sa.Column("summary", sa.Text, nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_job_scores_job_id", "job_scores", ["job_id"])
    op.create_index("ix_job_scores_user_id", "job_scores", ["user_id"])

    # --- cover_letters ------------------------------------------------
    op.create_table(
        "cover_letters",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("jobs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("tone", sa.String(20), nullable=False),
        sa.Column("length", sa.String(20), nullable=False),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_cover_letters_job_id", "cover_letters", ["job_id"])
    op.create_index("ix_cover_letters_user_id", "cover_letters", ["user_id"])

    # --- interview_events ---------------------------------------------
    op.create_table(
        "interview_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("jobs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer, nullable=False, server_default="60"),
        sa.Column("interview_type", sa.String(30), nullable=False),
        sa.Column("interviewer_name", sa.String(255), nullable=True),
        sa.Column("location_or_link", sa.String(500), nullable=True),
        sa.Column("google_event_id", sa.String(255), nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_interview_events_job_id", "interview_events", ["job_id"])
    op.create_index("ix_interview_events_user_id", "interview_events", ["user_id"])

    # --- company_research_cache ---------------------------------------
    op.create_table(
        "company_research_cache",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("company_name", sa.String(255), nullable=False, unique=True),
        sa.Column("research_data", postgresql.JSONB, nullable=False),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    # Order matters: drop dependents before parents.
    op.drop_table("company_research_cache")
    op.drop_table("interview_events")
    op.drop_table("cover_letters")
    op.drop_table("job_scores")
    op.drop_table("jobs")
    op.drop_table("profile_answers")
    op.drop_table("profiles")
    op.drop_table("users")
    # Leave pgcrypto installed — it may be used by future features and
    # dropping it would fail if anything else depends on it.
